# Generated by Django 4.2.30 on 2026-05-11 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteitem",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("pending", "Pending Review"),
                    ("reviewed", "Reviewed"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wasteitem",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wasteitem",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
